-- Seed data: the 6 bracelets. Run after schema.sql.

insert into products (slug, name, price, currency, category, stone, description, material, size, stock, images)
values
  ('rose-quartz', 'Rose Quartz Pembe Kuvars Doğal Taş Bileklik', 1000, 'TRY', 'bileklik', 'kuvars', 'Pembe kuvarsın yumuşak pembe tonlarını gold detaylarla buluşturan zarif ve romantik bir tasarım. Günlük kullanımda tek başına veya farklı bilekliklerle kombinlenebilir.', 'Pembe kuvars doğal taş boncuklar, gold renk metal bağlantı ve dekoratif geçmeli kapama.', '17–18 cm', 100, ARRAY['/images/rose-quartz-1.jpg']),
  ('pearl-leaf', 'Pearl Leaf İnci Detaylı Doğal Taş Bilezik', 1000, 'TRY', 'bileklik', 'inci', 'Doğal taş, inci ve yaprak figürünün bir araya geldiği özgün ve feminen bir tasarım. Organik formları ve gold görünümüyle zarif kombinleri tamamlar.', 'Açık renk doğal taş, doğal inci detayı, gold renk metal gövde ve yaprak figürü.', 'Ayarlanabilir / 17–18 cm', 100, ARRAY['/images/pearl-leaf-1.jpg', '/images/pearl-leaf-2.jpg', '/images/pearl-leaf-3.jpg']),
  ('lapis-blue', 'Lapis Blue Lapis Lazuli Doğal Taş Bileklik', 1000, 'TRY', 'bileklik', 'lapis', 'Lapis lazulinin yoğun mavi tonlarını gold detaylarla tamamlayan dikkat çekici bir tasarım. Güçlü renkleri sade kombinlere belirgin bir dokunuş katar.', 'Lapis lazuli doğal taş boncuklar, lacivert doğal taş disk ara parçalar, gold renk metal bağlantılar ve geçmeli kapama.', '17–18 cm', 100, ARRAY['/images/lapis-blue-1.jpg', '/images/lapis-blue-2.jpg', '/images/lapis-blue-3.jpg']),
  ('rhodonite-rose', 'Rhodonite Rose Doğal Taş Bileklik', 1000, 'TRY', 'bileklik', 'rodonit', 'Pembe kuvarsın açık tonlarıyla rodonitin desenli görünümünü bir araya getiren doğal taş bileklik. Vintage gold detayları tasarıma bohem bir karakter kazandırır.', 'Pembe kuvars ve rodonit doğal taş boncuklar, gold renk metal ara parçalar ve dekoratif geometrik kapama.', '17–18 cm', 100, ARRAY['/images/rhodonite-rose-1.jpg', '/images/rhodonite-rose-2.jpg', '/images/rhodonite-rose-3.jpg']),
  ('green-sun', 'Green Sun Yeşil Akik Doğal Taş Bileklik', 1000, 'TRY', 'bileklik', 'akik', 'Canlı yeşil doğal taşların açık renk detaylar ve gold güneş figürüyle buluştuğu enerjik bir tasarım. Özellikle yaz kombinlerine canlı ve özgün bir görünüm kazandırır.', 'Yeşil akik ve howlit doğal taş boncuklar, gold renk güneş figürü ve elastik yapı.', '17–18 cm', 100, ARRAY['/images/green-sun-1.jpg', '/images/green-sun-2.jpg', '/images/green-sun-3.jpg']),
  ('luna-turmalin', 'Luna Turmalin Doğal Taş Bileklik', 1000, 'TRY', 'bileklik', 'turmalin', 'Pembe, yeşil ve koyu tonlardaki doğal taşların gold hilal figürüyle tamamlandığı mistik ve feminen bir tasarım. Doğal renk geçişleri her bilekliğe özgün bir görünüm kazandırır.', 'Çok renkli turmalin doğal taş boncuklar, gold renk hilal figürü ve elastik yapı.', '17–18 cm', 100, ARRAY['/images/luna-turmalin-1.jpg', '/images/luna-turmalin-2.jpg']);
